plugins:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
  TargetRubyVersion: 2.6

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x

Minitest/MultipleAssertions:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/GuardClause:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false
